
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class AccountType
{

    public AccountType()
    {

        this.Accounts = new HashSet<Accounts>();

    }


    public int AccountTypeId { get; set; }

    public string Name { get; set; }



    public virtual ICollection<Accounts> Accounts { get; set; }

}

}
