
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class Accounts
{

    public Accounts()
    {

        this.Cards = new HashSet<Cards>();

        this.ClientRemittances = new HashSet<ClientRemittances>();

        this.Credit = new HashSet<Credit>();

        this.Deposit = new HashSet<Deposit>();

    }


    public System.Guid AccountId { get; set; }

    public System.Guid UserId { get; set; }

    public string Number { get; set; }

    public int Type { get; set; }

    public int Currency { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<decimal> OverdraftLimit { get; set; }

    public decimal Amount { get; set; }



    public virtual ICollection<Cards> Cards { get; set; }

    public virtual ICollection<ClientRemittances> ClientRemittances { get; set; }

    public virtual ICollection<Credit> Credit { get; set; }

    public virtual ICollection<Deposit> Deposit { get; set; }

    public virtual aspnet_Users aspnet_Users { get; set; }

    public virtual AccountType AccountType { get; set; }

}

}
