
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class Credit
{

    public Credit()
    {

        this.CreditOperations = new HashSet<CreditOperations>();

    }


    public System.Guid CreditId { get; set; }

    public System.Guid AccountId { get; set; }

    public string Number { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public System.DateTime NextPayDate { get; set; }

    public Nullable<decimal> SetCreditLimit { get; set; }

    public Nullable<decimal> MaxCreditLimit { get; set; }

    public decimal EndAmmount { get; set; }

    public System.Guid CreditPaymentId { get; set; }



    public virtual Accounts Accounts { get; set; }

    public virtual CreditPayments CreditPayments { get; set; }

    public virtual ICollection<CreditOperations> CreditOperations { get; set; }

}

}
