
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class Genre
{

    public Genre()
    {

        this.Albums = new HashSet<Album>();

    }


    public int GenreId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }



    public virtual ICollection<Album> Albums { get; set; }

}

}
