
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class Pattern
{

    public System.Guid Id { get; set; }

    public System.Guid UserId { get; set; }

    public string PayerSurname { get; set; }

    public string PayerName { get; set; }

    public string PayerPatronymic { get; set; }

    public string Account { get; set; }

    public string Card { get; set; }

    public string PaymentId { get; set; }

    public string PaymentName { get; set; }

    public string PersonalAccount { get; set; }

    public string ContractNumber { get; set; }

    public string CounterValue { get; set; }

    public string PatternName { get; set; }

}

}
