
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentsStage
{

    public int Id { get; set; }

    public int ParentStagesId { get; set; }

    public int NextStagesId { get; set; }

    public int PaymentsId { get; set; }

    public string Validator { get; set; }

    public string Prm001 { get; set; }

    public string Prm002 { get; set; }

    public string Prm003 { get; set; }

    public string Prm004 { get; set; }

    public string Prm005 { get; set; }

    public string Prm006 { get; set; }

    public string Prm007 { get; set; }

    public string Prm008 { get; set; }

    public string Prm009 { get; set; }

    public string Prm010 { get; set; }

    public string Description { get; set; }

}

}
