
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class TransferList
{

    public int id { get; set; }

    public string AccountFrom { get; set; }

    public string AccountTo { get; set; }

    public double TransferValue { get; set; }

    public string Currency { get; set; }

    public string UserFromId { get; set; }

    public string UserToId { get; set; }

}

}
