
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InternetBankingDal
{

using System;
    using System.Collections.Generic;
    
public partial class Vendor
{

    public int Id { get; set; }

    public string ShortName { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public int UNP { get; set; }

    public int DefaultCommitionId { get; set; }

}

}
